# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pd_database_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_one_record(object):
    def setupUi(self, one_record):
        one_record.setObjectName("one_record")
        one_record.setWindowModality(QtCore.Qt.ApplicationModal)
        one_record.resize(471, 381)
        self.verticalLayout = QtWidgets.QVBoxLayout(one_record)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(one_record)
        self.label_1.setMinimumSize(QtCore.QSize(100, 25))
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.label_show_id = QtWidgets.QLabel(one_record)
        self.label_show_id.setObjectName("label_show_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_show_id)
        self.label_2 = QtWidgets.QLabel(one_record)
        self.label_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_edit_fitting_name = QtWidgets.QLineEdit(one_record)
        self.line_edit_fitting_name.setObjectName("line_edit_fitting_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_fitting_name)
        self.label_3 = QtWidgets.QLabel(one_record)
        self.label_3.setMinimumSize(QtCore.QSize(100, 25))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_edit_fitting_friction_factor = QtWidgets.QLineEdit(one_record)
        self.line_edit_fitting_friction_factor.setObjectName("line_edit_fitting_friction_factor")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_fitting_friction_factor)
        self.label_4 = QtWidgets.QLabel(one_record)
        self.label_4.setMinimumSize(QtCore.QSize(100, 25))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.plain_text_edit_notes = QtWidgets.QPlainTextEdit(one_record)
        self.plain_text_edit_notes.setObjectName("plain_text_edit_notes")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plain_text_edit_notes)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(one_record)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(one_record)
        QtCore.QMetaObject.connectSlotsByName(one_record)

    def retranslateUi(self, one_record):
        _translate = QtCore.QCoreApplication.translate
        one_record.setWindowTitle(_translate("one_record", "One_Record"))
        self.label_1.setText(_translate("one_record", "Row ID"))
        self.label_show_id.setText(_translate("one_record", "TextLabel"))
        self.label_2.setText(_translate("one_record", "Fitting name"))
        self.label_3.setText(_translate("one_record", "Friction Factor"))
        self.label_4.setText(_translate("one_record", "Notes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    one_record = QtWidgets.QWidget()
    ui = Ui_one_record()
    ui.setupUi(one_record)
    one_record.show()
    sys.exit(app.exec_())
