# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PD_1.0.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 703)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Netherlands))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Netherlands))
        self.centralwidget.setObjectName("centralwidget")
        self.Input_PipeLine = QtWidgets.QGroupBox(self.centralwidget)
        self.Input_PipeLine.setGeometry(QtCore.QRect(10, 20, 300, 160))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Input_PipeLine.setFont(font)
        self.Input_PipeLine.setObjectName("Input_PipeLine")
        self.gridLayout_LineData = QtWidgets.QGridLayout(self.Input_PipeLine)
        self.gridLayout_LineData.setObjectName("gridLayout_LineData")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1.setIndent(6)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_LineData.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Line_Length = QtWidgets.QLineEdit(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Line_Length.setFont(font)
        self.Line_Length.setObjectName("Line_Length")
        self.verticalLayout_2.addWidget(self.Line_Length)
        self.Line_Diameter = QtWidgets.QLineEdit(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Line_Diameter.setFont(font)
        self.Line_Diameter.setObjectName("Line_Diameter")
        self.verticalLayout_2.addWidget(self.Line_Diameter)
        self.Line_WallRoughness = QtWidgets.QLineEdit(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Line_WallRoughness.setFont(font)
        self.Line_WallRoughness.setObjectName("Line_WallRoughness")
        self.verticalLayout_2.addWidget(self.Line_WallRoughness)
        self.gridLayout_LineData.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.gridLayout_LineData.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.gridLayout_LineData.setColumnMinimumWidth(1, 100)
        self.Input_Liquid = QtWidgets.QGroupBox(self.centralwidget)
        self.Input_Liquid.setGeometry(QtCore.QRect(430, 20, 400, 160))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Liquid.setFont(font)
        self.Input_Liquid.setObjectName("Input_Liquid")
        self.gridLayout_LiquidData = QtWidgets.QGridLayout(self.Input_Liquid)
        self.gridLayout_LiquidData.setObjectName("gridLayout_LiquidData")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setIndent(6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setIndent(6)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.gridLayout_LiquidData.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Liquid_Density = QtWidgets.QLineEdit(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_Density.setFont(font)
        self.Liquid_Density.setObjectName("Liquid_Density")
        self.verticalLayout_4.addWidget(self.Liquid_Density)
        self.Liquid_ViscDyn = QtWidgets.QLineEdit(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_ViscDyn.setFont(font)
        self.Liquid_ViscDyn.setObjectName("Liquid_ViscDyn")
        self.verticalLayout_4.addWidget(self.Liquid_ViscDyn)
        self.Liquid_ViscKin = QtWidgets.QLineEdit(self.Input_Liquid)
        self.Liquid_ViscKin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_ViscKin.setFont(font)
        self.Liquid_ViscKin.setObjectName("Liquid_ViscKin")
        self.verticalLayout_4.addWidget(self.Liquid_ViscKin)
        self.gridLayout_LiquidData.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.gridLayout_LiquidData.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.DynVisKnown = QtWidgets.QRadioButton(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.DynVisKnown.setFont(font)
        self.DynVisKnown.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.DynVisKnown.setChecked(True)
        self.DynVisKnown.setObjectName("DynVisKnown")
        self.verticalLayout_11.addWidget(self.DynVisKnown)
        self.KinViscKnown = QtWidgets.QRadioButton(self.Input_Liquid)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.KinViscKnown.setFont(font)
        self.KinViscKnown.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.KinViscKnown.setObjectName("KinViscKnown")
        self.verticalLayout_11.addWidget(self.KinViscKnown)
        self.gridLayout_LiquidData.addLayout(self.verticalLayout_11, 0, 3, 1, 1)
        self.gridLayout_LiquidData.setColumnMinimumWidth(0, 150)
        self.gridLayout_LiquidData.setColumnMinimumWidth(1, 80)
        self.Input_Flow = QtWidgets.QGroupBox(self.centralwidget)
        self.Input_Flow.setGeometry(QtCore.QRect(850, 20, 400, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Flow.setFont(font)
        self.Input_Flow.setObjectName("Input_Flow")
        self.gridLayout_FlowData = QtWidgets.QGridLayout(self.Input_Flow)
        self.gridLayout_FlowData.setObjectName("gridLayout_FlowData")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.gridLayout_FlowData.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Flow_Velocity = QtWidgets.QLineEdit(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Flow_Velocity.setFont(font)
        self.Flow_Velocity.setObjectName("Flow_Velocity")
        self.verticalLayout_8.addWidget(self.Flow_Velocity)
        self.Flow_Rate = QtWidgets.QLineEdit(self.Input_Flow)
        self.Flow_Rate.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Flow_Rate.setFont(font)
        self.Flow_Rate.setObjectName("Flow_Rate")
        self.verticalLayout_8.addWidget(self.Flow_Rate)
        self.gridLayout_FlowData.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.gridLayout_FlowData.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.VelocityKnown = QtWidgets.QRadioButton(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.VelocityKnown.setFont(font)
        self.VelocityKnown.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.VelocityKnown.setChecked(True)
        self.VelocityKnown.setObjectName("VelocityKnown")
        self.verticalLayout_10.addWidget(self.VelocityKnown)
        self.FlowRateKnown = QtWidgets.QRadioButton(self.Input_Flow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.FlowRateKnown.setFont(font)
        self.FlowRateKnown.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.FlowRateKnown.setObjectName("FlowRateKnown")
        self.verticalLayout_10.addWidget(self.FlowRateKnown)
        self.gridLayout_FlowData.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.gridLayout_FlowData.setColumnMinimumWidth(0, 150)
        self.gridLayout_FlowData.setColumnMinimumWidth(1, 80)
        self.Output = QtWidgets.QGroupBox(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(430, 210, 400, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Output.setFont(font)
        self.Output.setObjectName("Output")
        self.gridLayout = QtWidgets.QGridLayout(self.Output)
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.Output_LineVolume = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_LineVolume.setFont(font)
        self.Output_LineVolume.setIndent(10)
        self.Output_LineVolume.setObjectName("Output_LineVolume")
        self.gridLayout.addWidget(self.Output_LineVolume, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.Output_Reynolds = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Reynolds.setFont(font)
        self.Output_Reynolds.setIndent(10)
        self.Output_Reynolds.setObjectName("Output_Reynolds")
        self.gridLayout.addWidget(self.Output_Reynolds, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.Output_FlowRegime = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_FlowRegime.setFont(font)
        self.Output_FlowRegime.setIndent(10)
        self.Output_FlowRegime.setObjectName("Output_FlowRegime")
        self.gridLayout.addWidget(self.Output_FlowRegime, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 2, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 0, 1, 1)
        self.OUtput_ConduitType = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OUtput_ConduitType.setFont(font)
        self.OUtput_ConduitType.setIndent(10)
        self.OUtput_ConduitType.setObjectName("OUtput_ConduitType")
        self.gridLayout.addWidget(self.OUtput_ConduitType, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 3, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 0, 1, 1)
        self.Output_FrictionFactor = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_FrictionFactor.setFont(font)
        self.Output_FrictionFactor.setIndent(10)
        self.Output_FrictionFactor.setObjectName("Output_FrictionFactor")
        self.gridLayout.addWidget(self.Output_FrictionFactor, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 5, 0, 1, 1)
        self.Output_CalcMethod = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_CalcMethod.setFont(font)
        self.Output_CalcMethod.setIndent(10)
        self.Output_CalcMethod.setObjectName("Output_CalcMethod")
        self.gridLayout.addWidget(self.Output_CalcMethod, 5, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 5, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setText("")
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 6, 0, 1, 1)
        self.Output_Spare_1 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_1.setFont(font)
        self.Output_Spare_1.setText("")
        self.Output_Spare_1.setIndent(10)
        self.Output_Spare_1.setObjectName("Output_Spare_1")
        self.gridLayout.addWidget(self.Output_Spare_1, 6, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 6, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 180)
        self.Input_Values = QtWidgets.QGroupBox(self.centralwidget)
        self.Input_Values.setGeometry(QtCore.QRect(10, 210, 400, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Values.setFont(font)
        self.Input_Values.setObjectName("Input_Values")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Input_Values)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_38 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.Line_length_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Line_length_4Calc.setFont(font)
        self.Line_length_4Calc.setIndent(10)
        self.Line_length_4Calc.setObjectName("Line_length_4Calc")
        self.gridLayout_2.addWidget(self.Line_length_4Calc, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1)
        self.Line_Diameter_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Line_Diameter_4Calc.setFont(font)
        self.Line_Diameter_4Calc.setIndent(10)
        self.Line_Diameter_4Calc.setObjectName("Line_Diameter_4Calc")
        self.gridLayout_2.addWidget(self.Line_Diameter_4Calc, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 2, 1, 1, 1)
        self.Line_WallRoughness_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Line_WallRoughness_4Calc.setFont(font)
        self.Line_WallRoughness_4Calc.setIndent(10)
        self.Line_WallRoughness_4Calc.setObjectName("Line_WallRoughness_4Calc")
        self.gridLayout_2.addWidget(self.Line_WallRoughness_4Calc, 2, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 2, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 3, 1, 1, 1)
        self.Liquid_Density_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_Density_4Calc.setFont(font)
        self.Liquid_Density_4Calc.setIndent(10)
        self.Liquid_Density_4Calc.setObjectName("Liquid_Density_4Calc")
        self.gridLayout_2.addWidget(self.Liquid_Density_4Calc, 3, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 3, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 4, 1, 1, 1)
        self.Liquid_ViscDyn_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_ViscDyn_4Calc.setFont(font)
        self.Liquid_ViscDyn_4Calc.setIndent(10)
        self.Liquid_ViscDyn_4Calc.setObjectName("Liquid_ViscDyn_4Calc")
        self.gridLayout_2.addWidget(self.Liquid_ViscDyn_4Calc, 4, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 4, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 5, 1, 1, 1)
        self.Liquid_ViscKin_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_ViscKin_4Calc.setFont(font)
        self.Liquid_ViscKin_4Calc.setIndent(10)
        self.Liquid_ViscKin_4Calc.setObjectName("Liquid_ViscKin_4Calc")
        self.gridLayout_2.addWidget(self.Liquid_ViscKin_4Calc, 5, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 5, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 6, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 6, 1, 1, 1)
        self.Flow_Velocity_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Flow_Velocity_4Calc.setFont(font)
        self.Flow_Velocity_4Calc.setIndent(10)
        self.Flow_Velocity_4Calc.setObjectName("Flow_Velocity_4Calc")
        self.gridLayout_2.addWidget(self.Flow_Velocity_4Calc, 6, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 6, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 7, 1, 1, 1)
        self.Flow_Rate_4Calc = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Flow_Rate_4Calc.setFont(font)
        self.Flow_Rate_4Calc.setIndent(10)
        self.Flow_Rate_4Calc.setObjectName("Flow_Rate_4Calc")
        self.gridLayout_2.addWidget(self.Flow_Rate_4Calc, 7, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.Input_Values)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 7, 3, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(1, 150)
        self.gridLayout_2.setColumnMinimumWidth(2, 100)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(850, 210, 400, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.Output_PressureDrop = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_PressureDrop.setFont(font)
        self.Output_PressureDrop.setIndent(10)
        self.Output_PressureDrop.setObjectName("Output_PressureDrop")
        self.gridLayout_3.addWidget(self.Output_PressureDrop, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 1, 0, 1, 1)
        self.Output_PressureDrop_bar = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_PressureDrop_bar.setFont(font)
        self.Output_PressureDrop_bar.setIndent(10)
        self.Output_PressureDrop_bar.setObjectName("Output_PressureDrop_bar")
        self.gridLayout_3.addWidget(self.Output_PressureDrop_bar, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 1, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setText("")
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_3.addWidget(self.label_54, 2, 0, 1, 1)
        self.Output_Spare_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_2.setFont(font)
        self.Output_Spare_2.setText("")
        self.Output_Spare_2.setIndent(10)
        self.Output_Spare_2.setObjectName("Output_Spare_2")
        self.gridLayout_3.addWidget(self.Output_Spare_2, 2, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 2, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setText("")
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 3, 0, 1, 1)
        self.Output_Spare_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_3.setFont(font)
        self.Output_Spare_3.setText("")
        self.Output_Spare_3.setIndent(10)
        self.Output_Spare_3.setObjectName("Output_Spare_3")
        self.gridLayout_3.addWidget(self.Output_Spare_3, 3, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 3, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setText("")
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 4, 0, 1, 1)
        self.Output_Spare_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_4.setFont(font)
        self.Output_Spare_4.setText("")
        self.Output_Spare_4.setIndent(10)
        self.Output_Spare_4.setObjectName("Output_Spare_4")
        self.gridLayout_3.addWidget(self.Output_Spare_4, 4, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 4, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_60.setFont(font)
        self.label_60.setText("")
        self.label_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 5, 0, 1, 1)
        self.Output_Spare_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_5.setFont(font)
        self.Output_Spare_5.setText("")
        self.Output_Spare_5.setIndent(10)
        self.Output_Spare_5.setObjectName("Output_Spare_5")
        self.gridLayout_3.addWidget(self.Output_Spare_5, 5, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 5, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setText("")
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 6, 0, 1, 1)
        self.Output_Spare_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_6.setFont(font)
        self.Output_Spare_6.setText("")
        self.Output_Spare_6.setIndent(10)
        self.Output_Spare_6.setObjectName("Output_Spare_6")
        self.gridLayout_3.addWidget(self.Output_Spare_6, 6, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setText("")
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 6, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_64.setFont(font)
        self.label_64.setText("")
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 7, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setText("")
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 7, 2, 1, 1)
        self.Output_Spare_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Spare_7.setFont(font)
        self.Output_Spare_7.setText("")
        self.Output_Spare_7.setIndent(10)
        self.Output_Spare_7.setObjectName("Output_Spare_7")
        self.gridLayout_3.addWidget(self.Output_Spare_7, 7, 1, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 180)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 30))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuhelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Line_Length, self.Line_Diameter)
        MainWindow.setTabOrder(self.Line_Diameter, self.Line_WallRoughness)
        MainWindow.setTabOrder(self.Line_WallRoughness, self.Liquid_Density)
        MainWindow.setTabOrder(self.Liquid_Density, self.Liquid_ViscDyn)
        MainWindow.setTabOrder(self.Liquid_ViscDyn, self.Liquid_ViscKin)
        MainWindow.setTabOrder(self.Liquid_ViscKin, self.Flow_Velocity)
        MainWindow.setTabOrder(self.Flow_Velocity, self.Flow_Rate)
        MainWindow.setTabOrder(self.Flow_Rate, self.DynVisKnown)
        MainWindow.setTabOrder(self.DynVisKnown, self.KinViscKnown)
        MainWindow.setTabOrder(self.KinViscKnown, self.VelocityKnown)
        MainWindow.setTabOrder(self.VelocityKnown, self.FlowRateKnown)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SiPreDroCal  V-1.0"))
        self.Input_PipeLine.setTitle(_translate("MainWindow", "Pipe Line Data"))
        self.label_1.setText(_translate("MainWindow", "Length"))
        self.label_2.setText(_translate("MainWindow", "Hydrolic Diameter"))
        self.label_3.setText(_translate("MainWindow", "Wall Roughness"))
        self.label_4.setText(_translate("MainWindow", "m"))
        self.label_5.setText(_translate("MainWindow", "m"))
        self.label_6.setText(_translate("MainWindow", "m"))
        self.Input_Liquid.setTitle(_translate("MainWindow", "Liquid Data"))
        self.label_7.setText(_translate("MainWindow", "Density"))
        self.label_8.setText(_translate("MainWindow", "Dynamic Viscosity"))
        self.label_9.setText(_translate("MainWindow", "Kinematic Viscosity"))
        self.label_10.setText(_translate("MainWindow", "kg/m³"))
        self.label_11.setText(_translate("MainWindow", "Pas"))
        self.label_12.setText(_translate("MainWindow", "m²/s"))
        self.DynVisKnown.setText(_translate("MainWindow", "&Known"))
        self.KinViscKnown.setText(_translate("MainWindow", "K&nown"))
        self.Input_Flow.setTitle(_translate("MainWindow", "Flow Data"))
        self.label_13.setText(_translate("MainWindow", "Mean Velocity"))
        self.label_14.setText(_translate("MainWindow", "Flow Rate"))
        self.label_15.setText(_translate("MainWindow", "m/s"))
        self.label_16.setText(_translate("MainWindow", "m³/s"))
        self.VelocityKnown.setText(_translate("MainWindow", "&Known"))
        self.FlowRateKnown.setText(_translate("MainWindow", "K&nown"))
        self.Output.setTitle(_translate("MainWindow", "Calculation and Intermediate Values"))
        self.label_19.setText(_translate("MainWindow", "Line Volume"))
        self.Output_LineVolume.setText(_translate("MainWindow", "Unknown"))
        self.label_20.setText(_translate("MainWindow", "m³"))
        self.label_17.setText(_translate("MainWindow", "Reynolds Number"))
        self.Output_Reynolds.setText(_translate("MainWindow", "Unknown"))
        self.label_18.setText(_translate("MainWindow", "-"))
        self.label_21.setText(_translate("MainWindow", "Flow regime"))
        self.Output_FlowRegime.setText(_translate("MainWindow", "Unknown"))
        self.label_22.setText(_translate("MainWindow", "-"))
        self.label_23.setText(_translate("MainWindow", "Type of Conduit"))
        self.OUtput_ConduitType.setText(_translate("MainWindow", "Unknown"))
        self.label_24.setText(_translate("MainWindow", "-"))
        self.label_29.setText(_translate("MainWindow", "Darcy Friction Factor"))
        self.Output_FrictionFactor.setText(_translate("MainWindow", "Unknown"))
        self.label_30.setText(_translate("MainWindow", "-"))
        self.label_31.setText(_translate("MainWindow", "Calculation Method"))
        self.Output_CalcMethod.setText(_translate("MainWindow", "Unknown"))
        self.label_32.setText(_translate("MainWindow", "-"))
        self.Input_Values.setTitle(_translate("MainWindow", "Input "))
        self.label_38.setText(_translate("MainWindow", "Line"))
        self.label.setText(_translate("MainWindow", "length"))
        self.Line_length_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_50.setText(_translate("MainWindow", "m"))
        self.label_27.setText(_translate("MainWindow", "Diameter"))
        self.Line_Diameter_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_46.setText(_translate("MainWindow", "m"))
        self.label_28.setText(_translate("MainWindow", "Roughness"))
        self.Line_WallRoughness_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_47.setText(_translate("MainWindow", "m"))
        self.label_41.setText(_translate("MainWindow", "Liquid"))
        self.label_33.setText(_translate("MainWindow", "Density"))
        self.Liquid_Density_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_48.setText(_translate("MainWindow", "kg/m³"))
        self.label_34.setText(_translate("MainWindow", "Dynamic viscosity"))
        self.Liquid_ViscDyn_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_53.setText(_translate("MainWindow", "Pas"))
        self.label_35.setText(_translate("MainWindow", "Kinematic Viscosity"))
        self.Liquid_ViscKin_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_52.setText(_translate("MainWindow", "m²/s"))
        self.label_44.setText(_translate("MainWindow", "Flow"))
        self.label_36.setText(_translate("MainWindow", "Mean Velocity"))
        self.Flow_Velocity_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_51.setText(_translate("MainWindow", "m/s"))
        self.label_37.setText(_translate("MainWindow", "Rate"))
        self.Flow_Rate_4Calc.setText(_translate("MainWindow", "Unknown"))
        self.label_49.setText(_translate("MainWindow", "m³/s"))
        self.groupBox.setTitle(_translate("MainWindow", "Output"))
        self.label_25.setText(_translate("MainWindow", "Pressure Drop"))
        self.Output_PressureDrop.setText(_translate("MainWindow", "Unknown"))
        self.label_26.setText(_translate("MainWindow", "Pa"))
        self.label_43.setText(_translate("MainWindow", "Pressure Drop"))
        self.Output_PressureDrop_bar.setText(_translate("MainWindow", "Unknown"))
        self.label_42.setText(_translate("MainWindow", "bar"))
        self.menuhelp.setTitle(_translate("MainWindow", "He&lp"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

