# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PD_1.0.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Netherlands))
        self.centralwidget.setObjectName("centralwidget")
        self.Input_PipeLine = QtWidgets.QGroupBox(self.centralwidget)
        self.Input_PipeLine.setGeometry(QtCore.QRect(40, 20, 480, 160))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Input_PipeLine.setFont(font)
        self.Input_PipeLine.setObjectName("Input_PipeLine")
        self.gridLayout_LeidingGegevens = QtWidgets.QGridLayout(self.Input_PipeLine)
        self.gridLayout_LeidingGegevens.setObjectName("gridLayout_LeidingGegevens")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1.setIndent(6)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_LeidingGegevens.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Line_Length = QtWidgets.QLineEdit(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Line_Length.setFont(font)
        self.Line_Length.setObjectName("Line_Length")
        self.verticalLayout_2.addWidget(self.Line_Length)
        self.Line_Diameter = QtWidgets.QLineEdit(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Line_Diameter.setFont(font)
        self.Line_Diameter.setObjectName("Line_Diameter")
        self.verticalLayout_2.addWidget(self.Line_Diameter)
        self.Line_WallRoughness = QtWidgets.QLineEdit(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Line_WallRoughness.setFont(font)
        self.Line_WallRoughness.setObjectName("Line_WallRoughness")
        self.verticalLayout_2.addWidget(self.Line_WallRoughness)
        self.gridLayout_LeidingGegevens.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.Input_PipeLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.gridLayout_LeidingGegevens.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.gridLayout_LeidingGegevens.setColumnMinimumWidth(0, 180)
        self.gridLayout_LeidingGegevens.setColumnMinimumWidth(2, 150)
        self.Invoer_Vloeistof = QtWidgets.QGroupBox(self.centralwidget)
        self.Invoer_Vloeistof.setGeometry(QtCore.QRect(40, 210, 480, 160))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Invoer_Vloeistof.setFont(font)
        self.Invoer_Vloeistof.setObjectName("Invoer_Vloeistof")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Invoer_Vloeistof)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setIndent(6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setIndent(6)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Liquid_Density = QtWidgets.QLineEdit(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_Density.setFont(font)
        self.Liquid_Density.setObjectName("Liquid_Density")
        self.verticalLayout_4.addWidget(self.Liquid_Density)
        self.Liquid_ViscDyn = QtWidgets.QLineEdit(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_ViscDyn.setFont(font)
        self.Liquid_ViscDyn.setObjectName("Liquid_ViscDyn")
        self.verticalLayout_4.addWidget(self.Liquid_ViscDyn)
        self.Liquid_ViscKin = QtWidgets.QLineEdit(self.Invoer_Vloeistof)
        self.Liquid_ViscKin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Liquid_ViscKin.setFont(font)
        self.Liquid_ViscKin.setObjectName("Liquid_ViscKin")
        self.verticalLayout_4.addWidget(self.Liquid_ViscKin)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.DynVisBekend = QtWidgets.QRadioButton(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.DynVisBekend.setFont(font)
        self.DynVisBekend.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.DynVisBekend.setChecked(True)
        self.DynVisBekend.setObjectName("DynVisBekend")
        self.verticalLayout_11.addWidget(self.DynVisBekend)
        self.KinViscBekend = QtWidgets.QRadioButton(self.Invoer_Vloeistof)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.KinViscBekend.setFont(font)
        self.KinViscBekend.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.KinViscBekend.setObjectName("KinViscBekend")
        self.verticalLayout_11.addWidget(self.KinViscBekend)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 0, 3, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 180)
        self.gridLayout_3.setColumnMinimumWidth(2, 50)
        self.gridLayout_3.setColumnMinimumWidth(3, 100)
        self.Invoer_Stroming = QtWidgets.QGroupBox(self.centralwidget)
        self.Invoer_Stroming.setGeometry(QtCore.QRect(40, 420, 480, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Invoer_Stroming.setFont(font)
        self.Invoer_Stroming.setObjectName("Invoer_Stroming")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Invoer_Stroming)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Flow_Velocity = QtWidgets.QLineEdit(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Flow_Velocity.setFont(font)
        self.Flow_Velocity.setObjectName("Flow_Velocity")
        self.verticalLayout_8.addWidget(self.Flow_Velocity)
        self.Flow_Rate = QtWidgets.QLineEdit(self.Invoer_Stroming)
        self.Flow_Rate.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Flow_Rate.setFont(font)
        self.Flow_Rate.setObjectName("Flow_Rate")
        self.verticalLayout_8.addWidget(self.Flow_Rate)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.SnelheidBekend = QtWidgets.QRadioButton(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.SnelheidBekend.setFont(font)
        self.SnelheidBekend.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.SnelheidBekend.setChecked(True)
        self.SnelheidBekend.setObjectName("SnelheidBekend")
        self.verticalLayout_10.addWidget(self.SnelheidBekend)
        self.DebietBekend = QtWidgets.QRadioButton(self.Invoer_Stroming)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.DebietBekend.setFont(font)
        self.DebietBekend.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.DebietBekend.setObjectName("DebietBekend")
        self.verticalLayout_10.addWidget(self.DebietBekend)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 180)
        self.gridLayout_2.setColumnMinimumWidth(2, 50)
        self.gridLayout_2.setColumnMinimumWidth(3, 100)
        self.Output = QtWidgets.QGroupBox(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(539, 20, 411, 351))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Output.setFont(font)
        self.Output.setObjectName("Output")
        self.gridLayout = QtWidgets.QGridLayout(self.Output)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.Output_LineVolume = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_LineVolume.setFont(font)
        self.Output_LineVolume.setIndent(10)
        self.Output_LineVolume.setObjectName("Output_LineVolume")
        self.gridLayout.addWidget(self.Output_LineVolume, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.Output_Reynolds = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Reynolds.setFont(font)
        self.Output_Reynolds.setIndent(10)
        self.Output_Reynolds.setObjectName("Output_Reynolds")
        self.gridLayout.addWidget(self.Output_Reynolds, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.Output_FlowRegime = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_FlowRegime.setFont(font)
        self.Output_FlowRegime.setIndent(10)
        self.Output_FlowRegime.setObjectName("Output_FlowRegime")
        self.gridLayout.addWidget(self.Output_FlowRegime, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 2, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 0, 1, 1)
        self.OUtput_ConduitType = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OUtput_ConduitType.setFont(font)
        self.OUtput_ConduitType.setIndent(10)
        self.OUtput_ConduitType.setObjectName("OUtput_ConduitType")
        self.gridLayout.addWidget(self.OUtput_ConduitType, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 3, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 0, 1, 1)
        self.Output_FrictionFactor = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_FrictionFactor.setFont(font)
        self.Output_FrictionFactor.setIndent(10)
        self.Output_FrictionFactor.setObjectName("Output_FrictionFactor")
        self.gridLayout.addWidget(self.Output_FrictionFactor, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 5, 0, 1, 1)
        self.Output_CalcMethod = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_CalcMethod.setFont(font)
        self.Output_CalcMethod.setIndent(10)
        self.Output_CalcMethod.setObjectName("Output_CalcMethod")
        self.gridLayout.addWidget(self.Output_CalcMethod, 5, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 5, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 0, 1, 1)
        self.Output_PressureDrop = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_PressureDrop.setFont(font)
        self.Output_PressureDrop.setIndent(10)
        self.Output_PressureDrop.setObjectName("Output_PressureDrop")
        self.gridLayout.addWidget(self.Output_PressureDrop, 6, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.Output)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 6, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 30))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuhelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Line_Length, self.Line_Diameter)
        MainWindow.setTabOrder(self.Line_Diameter, self.Line_WallRoughness)
        MainWindow.setTabOrder(self.Line_WallRoughness, self.Liquid_Density)
        MainWindow.setTabOrder(self.Liquid_Density, self.Liquid_ViscDyn)
        MainWindow.setTabOrder(self.Liquid_ViscDyn, self.Liquid_ViscKin)
        MainWindow.setTabOrder(self.Liquid_ViscKin, self.Flow_Velocity)
        MainWindow.setTabOrder(self.Flow_Velocity, self.Flow_Rate)
        MainWindow.setTabOrder(self.Flow_Rate, self.DynVisBekend)
        MainWindow.setTabOrder(self.DynVisBekend, self.KinViscBekend)
        MainWindow.setTabOrder(self.KinViscBekend, self.SnelheidBekend)
        MainWindow.setTabOrder(self.SnelheidBekend, self.DebietBekend)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PD_V1.0"))
        self.Input_PipeLine.setTitle(_translate("MainWindow", "Pipe Line Data"))
        self.label_1.setText(_translate("MainWindow", "Length"))
        self.label_2.setText(_translate("MainWindow", "Hydrolic Diameter"))
        self.label_3.setText(_translate("MainWindow", "Wall Roughness"))
        self.label_4.setText(_translate("MainWindow", "m"))
        self.label_5.setText(_translate("MainWindow", "m"))
        self.label_6.setText(_translate("MainWindow", "m"))
        self.Invoer_Vloeistof.setTitle(_translate("MainWindow", "Liquid Data"))
        self.label_7.setText(_translate("MainWindow", "Density"))
        self.label_8.setText(_translate("MainWindow", "Dynamic Viscosity"))
        self.label_9.setText(_translate("MainWindow", "Kinematic Viscosity"))
        self.label_10.setText(_translate("MainWindow", "kg/m³"))
        self.label_11.setText(_translate("MainWindow", "Pas"))
        self.label_12.setText(_translate("MainWindow", "m²/s"))
        self.DynVisBekend.setText(_translate("MainWindow", "&Known"))
        self.KinViscBekend.setText(_translate("MainWindow", "K&nown"))
        self.Invoer_Stroming.setTitle(_translate("MainWindow", "Flow Data"))
        self.label_13.setText(_translate("MainWindow", "Mean Velocity"))
        self.label_14.setText(_translate("MainWindow", "Flow Rate"))
        self.label_15.setText(_translate("MainWindow", "m/s"))
        self.label_16.setText(_translate("MainWindow", "m³/s"))
        self.SnelheidBekend.setText(_translate("MainWindow", "Known"))
        self.DebietBekend.setText(_translate("MainWindow", "Known"))
        self.Output.setTitle(_translate("MainWindow", "Output"))
        self.label_19.setText(_translate("MainWindow", "Line Volume"))
        self.Output_LineVolume.setText(_translate("MainWindow", "Unknown"))
        self.label_20.setText(_translate("MainWindow", "m³"))
        self.label_17.setText(_translate("MainWindow", "Reynolds Number"))
        self.Output_Reynolds.setText(_translate("MainWindow", "Unknown"))
        self.label_18.setText(_translate("MainWindow", "-"))
        self.label_21.setText(_translate("MainWindow", "Flow regime"))
        self.Output_FlowRegime.setText(_translate("MainWindow", "Unknown"))
        self.label_22.setText(_translate("MainWindow", "-"))
        self.label_23.setText(_translate("MainWindow", "Type of Conduit"))
        self.OUtput_ConduitType.setText(_translate("MainWindow", "Unknown"))
        self.label_24.setText(_translate("MainWindow", "-"))
        self.label_29.setText(_translate("MainWindow", "Darcy Friction Factor"))
        self.Output_FrictionFactor.setText(_translate("MainWindow", "Unknown"))
        self.label_30.setText(_translate("MainWindow", "-"))
        self.label_31.setText(_translate("MainWindow", "Calculation Method"))
        self.Output_CalcMethod.setText(_translate("MainWindow", "Unknown"))
        self.label_32.setText(_translate("MainWindow", "-"))
        self.label_25.setText(_translate("MainWindow", "Pressure Drop"))
        self.Output_PressureDrop.setText(_translate("MainWindow", "Unknown"))
        self.label_26.setText(_translate("MainWindow", "Pa"))
        self.menuhelp.setTitle(_translate("MainWindow", "He&lp"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

